### ISSUE TITLE
不行运行

### ISSUE THREAD

**Issue by shzyxk** [yzbzz/beautifullife#1]
错误信息如下：

Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

不能运行

**Comment by yzbzz** [comment]
感谢提醒，已修复，自己学习的demo，代码较乱
